__title__ = "jtfo_logging"
__description__ = "JackTheFoxOtter's logging configuration"
__author__ = "JackTheFoxOtter"
__url__ = "https://github.com/JackTheFoxOtter/python-logging"
__license__ = "MIT"
__copyright__ = "Copyright 2023-present JackTheFoxOtter"
__version__ = "1.0.0"
